module.exports = {
  JJ: 'Adjective',
  JJR: 'Adjective, comparative',
  JJS: 'Adjective, superlative',
  NN: 'singular noun',
  NNS: 'plural noun',
  NNP: 'name of someone in the room',
  NNPS: 'name of a group of people',
  RB: 'Adverb',
  RBR: 'Adverb, comparative',
  RBS: 'Adverb, superlative',
  VB: 'Verb',
  VBD: 'Verb ending in -ed',
  VBG: 'Verb ending in -ing',
  VBN: 'Verb, past participle',
  VBP: 'Verb, present tense You, I, or We',
  VBZ: 'Verb, present tense',
}
